config/routes.rb
Rails.application.routes.draw do
  root to: 'pets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :found_on, presence: true
  validates :address, presence: true
  validates :color, presence: true

  validates :species, inclusion: { in: %w[dog cat rabbit bird] }

  def found_days_ago
    "#{(Date.today - found_on).to_i} days ago"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  def index
    @pets = Pet.all
  end

  def show; end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save

    redirect_to pet_path(@pet)
  end

  def edit; end

  def update
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to root_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :species, :color, :found_on, :address, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for(pet) do |f| %>
  <%= f.input :name %>
  <%= f.input :species %>
  <%= f.input :color %>
  <%= f.input :found_on %>
  <%= f.input :address %>
  <%# <%= f.input :image %>
  <%= f.simple_fields_for :image do |af| %>
        <%= af.input :photo, as: :file, label: :image, required: true, id: :image %>
      <% end %>
  <%= f.submit class: 'btn btn-success mb-5'%>
<% end %>

app/views/pets/edit.html.erb
<div class="container">
  <div class="top-margin">
    <h1>Update Pet Data</h1>
    <%= render "form", pet: @pet %>
  </div>
</div>

app/views/pets/index.html.erb
<div class="jumbotron jumbotron-fluid">
<%= link_to 'List a lost pet', new_pet_path, class: 'flex-row-reverse btn btn-light float-right mx-5' %>
  <div class="container">
    <h1 class="display-4">Lost Pets in Tokyo</h1>
    <p class="lead">Lost a pet? Found a pet? List or find them here.</p>
  </div>
</div>
<div class="container">
  <div class="row">
    <%  @pets.each do |pet|%>
    <div class="col-12 col-md-6 col-lg-4">
          <div class="card mb-3 shadow-sm">
            <div class="card-body">
              <img src=<%= pet.image %> alt="pet photo" class="rounded float-right">
              <h5 class="card-title"><%= pet.name %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= pet.species.capitalize %></h6>
              <p class="card-text">📍 <%= pet.address %></p>
              <p class="card-text">
                <% if pet.found_days_ago == '0 days ago' %>
                  <p>This pet was found today</p>
                <% else %>
                  <p>This pet was found <%= pet.found_days_ago %></li>
                <% end %>
              </p>
              <%= link_to 'Details', pet_path(pet), class: "card-link" %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/pets/new.html.erb
<div class="container">
  <div class="top-margin">
    <h1>Add a Lost Pet</h1>
    <%= render "form", pet: @pet %>
  </div>
</div>

app/views/pets/show.html.erb
<h1 class="pet-header"><%= @pet.name %></h1>
<div class="container">
  <div class="top-margin row">
    <div class="col-12 col-md-12 col-lg-8 mx-auto">
      <div class="pet-details shadow-sm mb-5">
        <h3><%= @pet.name %>'s Details</h3>
        <img src=<%= @pet.image %> style="width: 200px; height: 200px;" alt="pet photo" class="rounded float-right">
        <ul class="list-unstyled">
          <li><strong>Species:</strong> <%= @pet.species.capitalize %></li>
          <li><strong>Color:</strong> <%= @pet.color.capitalize %></li>
          <li><strong>Found at:</strong> <%= @pet.address %></li>
          <% if @pet.found_days_ago == '0 days ago' %>
            <li>This pet was found today</li>
          <% elsif @pet.found_days_ago == '1 days ago' %>
            <li>This pet was found yesterday </li>
          <% else %>
            <li>This pet was found <%= @pet.found_days_ago %></li>
          <% end %>
        </ul>
        <%= link_to 'Unlist This Pet', pet_path(@pet), method: :delete, data: { confirm: "Delete?" } , class: "btn btn-warning mb-3" %><br>
        <%= link_to 'Go Back', root_path, class: 'card-link border-right pr-3' %>
        <%= link_to 'Update Pet', edit_pet_path, class: 'card-link pr-3 border-right' %>
        <%= link_to 'Contact', edit_pet_path, class: 'card-link pr-3' %>
        <%# some kind of mailer or contact form %>
      </div>
    </div>
  </div>
</div>